pipeline:
  build:
    image: node:latest
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: axelmoussard/webpagesurv-app
    tags: [ latest ]
    username: amoussard
    password: moabistudio